package com.commercetools.sunrise.search.facetedsearch;

public interface ConfiguredFacetedSearchFormSettingsWithOptions extends ConfiguredFacetedSearchFormSettings, BaseFacetedSearchWithOptions {

}
